import type { Archetype } from "./types";

export interface RosterEntry {
  id: number;
  firstName: string;
  nickname: string;
  lastName: string;
  archetype: Archetype;
  isKeyFighter: boolean;
  forceUndefeated: boolean;
  fixedRank?: number;
  highWinRatio?: boolean;
  alwaysUndefeated?: boolean;
}

const A: Archetype[] = ["BoxerPuncher", "OutBoxer", "Brawler", "Swarmer"];

function assignArch(id: number): Archetype {
  const patterns: Record<number, Archetype> = {
    1: "BoxerPuncher", 2: "OutBoxer", 3: "Brawler", 4: "Swarmer",
    5: "Brawler", 6: "BoxerPuncher", 7: "OutBoxer", 8: "Swarmer",
    41: "OutBoxer", 131: "Brawler", 152: "BoxerPuncher", 166: "Brawler",
    197: "OutBoxer", 204: "BoxerPuncher",
  };
  if (patterns[id]) return patterns[id];
  return A[(id * 7 + 3) % 4];
}

function parseEntry(id: number, raw: string): RosterEntry {
  const cleaned = raw.replace(/\s*\([^)]+\)/g, "").trim();
  const nicknameMatch = cleaned.match(/"([^"]+)"/);
  const nickname = nicknameMatch ? nicknameMatch[1] : "";
  const withoutNickname = cleaned.replace(/"[^"]+"\s*/, "").trim();
  const parts = withoutNickname.split(/\s+/);
  const firstName = parts[0] || "";
  const lastName = parts.slice(1).join(" ") || "";

  const KEY_IDS = [1, 41, 131, 152, 166, 197, 204];
  const isKey = KEY_IDS.includes(id);

  return {
    id,
    firstName,
    nickname,
    lastName,
    archetype: assignArch(id),
    isKeyFighter: isKey,
    forceUndefeated: isKey,
    fixedRank: id === 204 ? 1 : undefined,
    highWinRatio: false,
    alwaysUndefeated: false,
  };
}

export const ROSTER_DATA: RosterEntry[] = [
  parseEntry(1, 'Mario Holmes'),
  parseEntry(2, 'Andre "Iron Pulse" Vega'),
  parseEntry(3, 'Darius Knox'),
  parseEntry(4, 'Leon "Southpaw Phantom" Cruz'),
  parseEntry(5, 'Vlad Furyk'),
  parseEntry(6, 'Marvin "Night Engine" Carter'),
  parseEntry(7, 'Rafael Stone'),
  parseEntry(8, 'Julian "Quick Verdict" Price'),
  parseEntry(9, 'DeShawn Wildero'),
  parseEntry(10, 'Victor "Riot Hook" Salazar'),
  parseEntry(11, 'Caleb Johnson'),
  parseEntry(12, 'Roman "Cold Equation" Petrov'),
  parseEntry(13, 'Terrence Maystorm'),
  parseEntry(14, 'Isaiah "Flashpoint" Reed'),
  parseEntry(15, 'Dominic Vance'),
  parseEntry(16, 'Hector "Grim Tempo" Ruiz'),
  parseEntry(17, 'Lennox Alvarado'),
  parseEntry(18, 'Quentin "Razor Choir" Banks'),
  parseEntry(19, 'Omar Briggs'),
  parseEntry(20, 'Xavier "Blackout Theory" Shaw'),
  parseEntry(21, 'Anthony Kovalevson'),
  parseEntry(22, 'Gabriel "Velvet Hammer" King'),
  parseEntry(23, 'Jamal Ortiz'),
  parseEntry(24, 'Nikolai "Red Comet" Sokolov'),
  parseEntry(25, 'Brandon Hale'),
  parseEntry(26, 'Elias "Bone Collector" Ward'),
  parseEntry(27, 'Curtis Bennett'),
  parseEntry(28, 'Dante "Chrome Fist" Morales'),
  parseEntry(29, 'Floydrick Caneloza'),
  parseEntry(30, 'Adrian "Sudden Silence" Cole'),
  parseEntry(31, 'Trevor Lang'),
  parseEntry(32, 'Micah "Ghost Ledger" Boone'),
  parseEntry(33, 'Sergio Dalton'),
  parseEntry(34, 'Byron "Crimson Orbit" Hayes'),
  parseEntry(35, 'Peter Grant'),
  parseEntry(36, 'Khalil "War Psalm" Hodge'),
  parseEntry(37, 'Ruben Castillo'),
  parseEntry(38, 'Marcus "Hard Reset" Doyle'),
  parseEntry(39, 'Edwin Brooks'),
  parseEntry(40, 'Theo "Ivory Avalanche" Laurent'),
  parseEntry(41, 'Calvin Price'),
  parseEntry(42, 'Zaire "Midnight Verdict" Okoye'),
  parseEntry(43, 'Harold Finch'),
  parseEntry(44, 'Nico "Switchblade" Marquez'),
  parseEntry(45, 'Michael "Steel Mirage" Barrow'),
  parseEntry(46, 'Aaron Pike'),
  parseEntry(47, 'Ian Fletcher'),
  parseEntry(48, 'Shawn Porterfield'),
  parseEntry(49, 'Devon Mercer'),
  parseEntry(50, 'Victor "Iron Sabbath" Kane'),
  parseEntry(51, 'Connor Blake'),
  parseEntry(52, 'Terrence Cole'),
  parseEntry(53, 'Ryan O\'Connell'),
  parseEntry(54, 'Andre "Zero Mercy" Baptiste'),
  parseEntry(55, 'Stefan Ionescu'),
  parseEntry(56, 'Darius "Black Templar" Graves'),
  parseEntry(57, 'Miguel Santos'),
  parseEntry(58, 'Jamal "Heatwave Prophet" Bishop'),
  parseEntry(59, 'Trevor Mills'),
  parseEntry(60, 'Isaiah "Rogue Current" Maddox'),
  parseEntry(61, 'Roland Pierce'),
  parseEntry(62, 'Hector "Silent Riot" Navarro'),
  parseEntry(63, 'Samuel Turner'),
  parseEntry(64, 'Leon "Graveyard Shift" Booker'),
  parseEntry(65, 'Vincent Cole'),
  parseEntry(66, 'Arman "Titan Echo" Petrosyan'),
  parseEntry(67, 'Curtis Shaw'),
  parseEntry(68, 'DeAndre "Voltage Viper" Quinn'),
  parseEntry(69, 'Felix Moreno'),
  parseEntry(70, 'Terrence "Savage Arithmetic" Sloan'),
  parseEntry(71, 'Bradley Kent'),
  parseEntry(72, 'Roman "Nightfall Atlas" Volkov'),
  parseEntry(73, 'Shawn Ellis'),
  parseEntry(74, 'Darnell "Iron Howl" Briggs'),
  parseEntry(75, 'Patrick Doyle'),
  parseEntry(76, 'Zane "Obsidian Halo" Cross'),
  parseEntry(77, 'Henry Collins'),
  parseEntry(78, 'Dante "Solar Flare" Whitaker'),
  parseEntry(79, 'Oscar DeLomachenko'),
  parseEntry(80, 'Thomas "Storm Cipher" Ramsey'),
  parseEntry(81, 'Jason Reed'),
  parseEntry(82, 'Rafael "Cinder King" Alvarez'),
  parseEntry(83, 'Corey Mitchell'),
  parseEntry(84, 'Andre "Velcro Jab" Hudson'),
  parseEntry(85, 'Nathan Brooks'),
  parseEntry(86, 'Isaiah "Blood Moon" Carter'),
  parseEntry(87, 'Tyler Grant'),
  parseEntry(88, 'Dominic "Rogue Doctrine" Silva'),
  parseEntry(89, 'Caleb Ross'),
  parseEntry(90, 'Viktor "Hammer Doctrine" Kravtsov'),
  parseEntry(91, 'Julian Harper'),
  parseEntry(92, 'Xavier "Shock Sermon" Tate'),
  parseEntry(93, 'Brian Foster'),
  parseEntry(94, 'Lennox "Granite Gospel" Wright'),
  parseEntry(95, 'Eric Dawson'),
  parseEntry(96, 'Omar "Thunder Psalm" Haddad'),
  parseEntry(97, 'Cody Marshall'),
  parseEntry(98, 'Cody "Neptune Knuckles" Thomas'),
  parseEntry(99, 'George Hill'),
  parseEntry(100, 'Andre "Black Ice" Monroe'),
  parseEntry(101, 'Scott Jenkins'),
  parseEntry(102, 'Marcus "Grim Symphony" Rowe'),
  parseEntry(103, 'Daniel Price'),
  parseEntry(104, 'Hector "Atlas Breaker" Dominguez'),
  parseEntry(105, 'Kevin Ward'),
  parseEntry(106, 'Leon "Tempest Choir" Maddox'),
  parseEntry(107, 'Chris Nolan'),
  parseEntry(108, 'Darius "Riot Architect" Sloan'),
  parseEntry(109, 'Matthew Cole'),
  parseEntry(110, 'Jamal "Midnight Furnace" Ellis'),
  parseEntry(111, 'Brandon Scott'),
  parseEntry(112, 'Roman "Ivory Execution" Dragunov'),
  parseEntry(113, 'Luke Perry'),
  parseEntry(114, 'Caleb "Stone Prophet" Hayes'),
  parseEntry(115, 'Michael Torres'),
  parseEntry(116, 'Andre "Phantom Pressure" Knox'),
  parseEntry(117, 'Anthony Furyweather'),
  parseEntry(118, 'Zaire "Dark Matter" King'),
  parseEntry(119, 'Thomas Reed'),
  parseEntry(120, 'Ezekiel "Voltage Requiem" Stone'),
  parseEntry(121, 'Paul Harris'),
  parseEntry(122, 'Hector "Brass Tyrant" Vega'),
  parseEntry(123, 'Jonathan Clark'),
  parseEntry(124, 'Leon "North Star Nightmare" Cruz'),
  parseEntry(125, 'David Turner'),
  parseEntry(126, 'Dante "Black Cathedral" Vance'),
  parseEntry(127, 'Mark Lewis'),
  parseEntry(128, 'Nathan "Spider" Romanov'),
  parseEntry(129, 'Jason Clark'),
  parseEntry(130, 'Isaiah "Grim Static" Boone'),
  parseEntry(131, 'Steven Smith'),
  parseEntry(132, 'Rafael "Iron Oracle" Castillo'),
  parseEntry(133, 'Steven Moore'),
  parseEntry(134, 'Andre "Savage Paradox" Bennett'),
  parseEntry(135, 'Adam White'),
  parseEntry(136, 'Darius "War Algorithm" Price'),
  parseEntry(137, 'Kyle Young'),
  parseEntry(138, 'Brett "Chrome Tempest" Reed'),
  parseEntry(139, 'Justin Hall'),
  parseEntry(140, 'Leon "Ghost Hammer" Shaw'),
  parseEntry(141, 'Eric Brown'),
  parseEntry(142, 'Roman "Cold Blood Opera" Sidorov'),
  parseEntry(143, 'Nathan Green'),
  parseEntry(144, 'Jamal "Oblivion Hook" Pierce'),
  parseEntry(145, 'Aaron Scott'),
  parseEntry(146, 'Hector "Iron Eclipse" Navarro'),
  parseEntry(147, 'Kevin Lee Jr.'),
  parseEntry(148, 'Dante "Static Titan" Brooks'),
  parseEntry(149, 'Brian King'),
  parseEntry(150, 'Gray "Blackout" Mercer'),
  parseEntry(151, 'Chris Evans'),
  parseEntry(152, 'Andre "Night Engine X" Carter'),
  parseEntry(153, 'Victor Drago Jr.'),
  parseEntry(154, 'Nick "Quantum Knuckle" Zaire'),
  parseEntry(155, 'Leonidas "Starlight Mauler" Rex'),
  parseEntry(156, 'Orion "Galactic Bruiser" Voss'),
  parseEntry(157, 'Ezekiel "Thunder Gospel" Cain'),
  parseEntry(158, 'Atlas Stone'),
  parseEntry(159, 'Phoenix "Solar Executioner" Raines'),
  parseEntry(160, 'Nova "Meteor Jab" Kade'),
  parseEntry(161, 'Magnus "Iron Seraph" Voltaire'),
  parseEntry(162, 'Ajax Fury'),
  parseEntry(163, 'Darius "Emerald Guillotine" Vale'),
  parseEntry(164, 'Andre "Crimson Theory" Locke'),
  parseEntry(165, 'Nick "Ivory Rapture" Knox'),
  parseEntry(166, 'Leon "Iron" Ward'),
  parseEntry(167, 'Richard "Gravity" Briggs'),
  parseEntry(168, 'Hector "Mirage" Cruz'),
  parseEntry(169, 'Roman "Orbit" Petrov'),
  parseEntry(170, 'Jamal "The Sun" Carter'),
  parseEntry(171, 'Caleb "Granite Phantom" Ross'),
  parseEntry(172, 'Rafael "Cinder Prophet" Morales'),
  parseEntry(173, 'Andre Bennett'),
  parseEntry(174, 'Esteban Ochoa'),
  parseEntry(175, 'Leon Cruz'),
  parseEntry(176, 'Hector Ruiz'),
  parseEntry(177, 'Roman Petrov'),
  parseEntry(178, 'Jamal Bishop'),
  parseEntry(179, 'Caleb Ward'),
  parseEntry(180, 'Rafael Stone'),
  parseEntry(181, 'Hugo Kane'),
  parseEntry(182, 'Dante Morales'),
  parseEntry(183, 'Isaiah Reed'),
  parseEntry(184, 'Victor Salazar'),
  parseEntry(185, 'Marcus Doyle'),
  parseEntry(186, 'Omar Haddad'),
  parseEntry(187, 'Zane Cross'),
  parseEntry(188, 'Darius Knox'),
  parseEntry(189, 'Frank Stroud'),
  parseEntry(190, 'Andre Hudson'),
  parseEntry(191, 'Leon Booker'),
  parseEntry(192, 'Hector Dominguez'),
  parseEntry(193, 'Roman Volkov'),
  parseEntry(194, 'Jamal Sloan'),
  parseEntry(195, 'Caleb Hayes'),
  parseEntry(196, 'Rafael Alvarez'),
  parseEntry(197, 'Floyd Vale'),
  parseEntry(198, 'Dante Whitaker'),
  parseEntry(199, 'Isaiah Carter'),
  parseEntry(200, 'Malik Ramsey'),
  parseEntry(201, 'Andre Baptiste'),
  parseEntry(202, 'Leon Maddox'),
  parseEntry(203, 'Nino "Nightmare" Black'),
  parseEntry(204, 'Wolfgang "Superman" Aruzenai Jr.'),
  // --- NEW FIGHTERS: File 1 — North America (IDs 205–404) ---
  parseEntry(205, 'Marcus "Stone" Carter'),
  parseEntry(206, 'Darius "Ghost" Brooks'),
  parseEntry(207, 'Anthony Rivera'),
  parseEntry(208, 'Jamal "Blaze" Porter'),
  parseEntry(209, 'Eric Simmons'),
  parseEntry(210, 'Devon "Ice" Hayes'),
  parseEntry(211, 'Isaiah Coleman'),
  parseEntry(212, 'Tyrell "Steel" Davis'),
  parseEntry(213, 'Andre Miller'),
  parseEntry(214, 'Caleb "Flash" Grant'),
  parseEntry(215, 'Xavier Johnson'),
  parseEntry(216, 'Leon "Smoke" Harris'),
  parseEntry(217, 'Brandon Lewis'),
  parseEntry(218, 'Mason "Bullet" Ward'),
  parseEntry(219, 'Elijah Foster'),
  parseEntry(220, 'Trevor "Wolf" Knight'),
  parseEntry(221, 'Jordan Reed'),
  parseEntry(222, 'Damon "Viper" Price'),
  parseEntry(223, 'Quentin Moore'),
  parseEntry(224, 'Malik "Jet" Turner'),
  parseEntry(225, 'Christian Scott'),
  parseEntry(226, 'Noah Barnes'),
  parseEntry(227, 'Elijah "Hammer" Collins'),
  parseEntry(228, 'Cameron Brooks'),
  parseEntry(229, 'Devon "Edge" Parker'),
  parseEntry(230, 'Marcus Young'),
  parseEntry(231, 'Tyler "Venom" Ross'),
  parseEntry(232, 'Ethan Bailey'),
  parseEntry(233, 'Nathan Cole'),
  parseEntry(234, 'Chase "Crusher" Hill'),
  parseEntry(235, 'Austin Bell'),
  parseEntry(236, 'Bryce Evans'),
  parseEntry(237, 'Luke Morris'),
  parseEntry(238, 'Connor Adams'),
  parseEntry(239, 'Cody Stewart'),
  parseEntry(240, 'Blake "Razor" Morgan'),
  parseEntry(241, 'Hunter Kelly'),
  parseEntry(242, 'Dylan Price'),
  parseEntry(243, 'Logan Turner'),
  parseEntry(244, 'Mason Gray'),
  parseEntry(245, 'Carter Bishop'),
  parseEntry(246, 'Jalen "Rogue" Mitchell'),
  parseEntry(247, 'Terrence White'),
  parseEntry(248, 'Dominic Allen'),
  parseEntry(249, 'Corey "Titan" Hill'),
  parseEntry(250, 'Cameron Ellis'),
  parseEntry(251, 'Victor Cruz'),
  parseEntry(252, 'Julian Foster'),
  parseEntry(253, 'DeShawn "Bolt" Hughes'),
  parseEntry(254, 'Roman Walker'),
  parseEntry(255, 'Isaac Reed'),
  parseEntry(256, 'Mason "Rook" Brooks'),
  parseEntry(257, 'Jeremiah Woods'),
  parseEntry(258, 'Trevor Mills'),
  parseEntry(259, 'Zachary Clark'),
  parseEntry(260, 'Adrian King'),
  parseEntry(261, 'Shawn Carter'),
  parseEntry(262, 'Jordan "Knockout" Briggs'),
  parseEntry(263, 'Tyson Cole'),
  parseEntry(264, 'Aaron Bell'),
  parseEntry(265, 'Xavier "Ace" Grant'),
  parseEntry(266, 'Devin Nash'),
  parseEntry(267, 'Michael Hunter'),
  parseEntry(268, 'Isaiah Price'),
  parseEntry(269, 'Dante "Savage" Banks'),
  parseEntry(270, 'Calvin Brooks'),
  parseEntry(271, 'Riley Stone'),
  parseEntry(272, 'Eric Fields'),
  parseEntry(273, 'Malik Dawson'),
  parseEntry(274, 'Kevin "Storm" Hayes'),
  parseEntry(275, 'Andre Carson'),
  parseEntry(276, 'Joshua Bell'),
  parseEntry(277, 'Trent Williams'),
  parseEntry(278, 'Damian Rhodes'),
  parseEntry(279, 'Jason "Heat" Foster'),
  parseEntry(280, 'Omar Pierce'),
  parseEntry(281, 'Curtis Blake'),
  parseEntry(282, 'Nathaniel Moss'),
  parseEntry(283, 'Christian Ray'),
  parseEntry(284, 'Devon Holt'),
  parseEntry(285, 'Caleb Mercer'),
  parseEntry(286, 'Bryce Carter Jr.'),
  parseEntry(287, 'Jordan Ellis Jr.'),
  parseEntry(288, 'Marcus Porter Jr.'),
  parseEntry(289, 'Anthony Brooks Jr.'),
  parseEntry(290, 'Darius Hayes Jr.'),
  parseEntry(291, 'Cameron Bell Jr.'),
  parseEntry(292, 'Elijah Simmons Jr.'),
  parseEntry(293, 'Jamal Foster Jr.'),
  parseEntry(294, 'Isaiah Mitchell III'),
  parseEntry(295, 'Caleb Johnson III'),
  parseEntry(296, 'Marcus Carter III'),
  parseEntry(297, 'Xavier Brooks IV'),
  parseEntry(298, 'Tyler Evans'),
  parseEntry(299, 'Connor Fields'),
  parseEntry(300, 'Jordan Mills'),
  parseEntry(301, 'Aaron Price'),
  parseEntry(302, 'Victor Lane'),
  parseEntry(303, 'Cody Nash'),
  parseEntry(304, 'Trevor Reed'),
  parseEntry(305, 'Brandon Miles'),
  parseEntry(306, 'Ethan Grant'),
  parseEntry(307, 'Hunter Davis'),
  parseEntry(308, 'Logan Scott'),
  parseEntry(309, 'Luke Carson'),
  parseEntry(310, 'Carter Hayes'),
  parseEntry(311, 'Noah Brooks'),
  parseEntry(312, 'Bryce Turner'),
  parseEntry(313, 'Austin Miller'),
  parseEntry(314, 'Mason Lewis'),
  parseEntry(315, 'Caleb Stone'),
  parseEntry(316, 'Devon Parker'),
  parseEntry(317, 'Andre Ross'),
  parseEntry(318, 'Xavier Woods'),
  parseEntry(319, 'Tyson Reed'),
  parseEntry(320, 'Nathan Hill'),
  parseEntry(321, 'Dylan Carter'),
  parseEntry(322, 'Shawn Briggs'),
  parseEntry(323, 'Damian Brooks'),
  parseEntry(324, 'Roman Ellis'),
  parseEntry(325, 'Quentin Hayes'),
  parseEntry(326, 'Isaiah King'),
  parseEntry(327, 'Christian Walker'),
  parseEntry(328, 'Cameron Grant'),
  parseEntry(329, 'Trevor White'),
  parseEntry(330, 'Eric Bell'),
  parseEntry(331, 'Caleb Ross'),
  parseEntry(332, 'Aaron Cole'),
  parseEntry(333, 'Michael Price'),
  parseEntry(334, 'Jordan Barnes'),
  parseEntry(335, 'Logan Mitchell'),
  parseEntry(336, 'Elijah Davis'),
  parseEntry(337, 'Dominic Brooks'),
  parseEntry(338, 'Austin Reed'),
  parseEntry(339, 'Chase Turner'),
  parseEntry(340, 'Tyler Morgan'),
  parseEntry(341, 'Brandon Fields'),
  parseEntry(342, 'Carter Bell'),
  parseEntry(343, 'Blake Foster'),
  parseEntry(344, 'Victor Hayes'),
  parseEntry(345, 'Marcus Gray'),
  parseEntry(346, 'Darius Reed'),
  parseEntry(347, 'Anthony Nash'),
  parseEntry(348, 'Jamal Woods'),
  parseEntry(349, 'Xavier Price'),
  parseEntry(350, 'Tyson Walker'),
  parseEntry(351, 'Devon King'),
  parseEntry(352, 'Bryce Hill'),
  parseEntry(353, 'Connor Lewis'),
  parseEntry(354, 'Hunter Grant'),
  parseEntry(355, 'Mason Ellis'),
  parseEntry(356, 'Noah Turner'),
  parseEntry(357, 'Caleb White'),
  parseEntry(358, 'Aaron Brooks'),
  parseEntry(359, 'Eric Carter'),
  parseEntry(360, 'Christian Hayes'),
  parseEntry(361, 'Trevor Cole'),
  parseEntry(362, 'Damian Bell'),
  parseEntry(363, 'Roman Fields'),
  parseEntry(364, 'Logan Price'),
  parseEntry(365, 'Tyler Scott'),
  parseEntry(366, 'Brandon Ellis'),
  parseEntry(367, 'Chase Brooks'),
  parseEntry(368, 'Austin Hayes'),
  parseEntry(369, 'Victor Ross'),
  parseEntry(370, 'Nathan Carter'),
  parseEntry(371, 'Michael Turner'),
  parseEntry(372, 'Shawn Walker'),
  parseEntry(373, 'Jordan Lewis'),
  parseEntry(374, 'Cameron Price'),
  parseEntry(375, 'Tyson Grant'),
  parseEntry(376, 'Bryce Cole'),
  parseEntry(377, 'Hunter Bell'),
  parseEntry(378, 'Elijah King'),
  parseEntry(379, 'Xavier Fields'),
  parseEntry(380, 'Devon Brooks'),
  parseEntry(381, 'Caleb Turner'),
  parseEntry(382, 'Aaron White'),
  parseEntry(383, 'Logan Carter'),
  parseEntry(384, 'Mason Ross'),
  parseEntry(385, 'Tyler Davis'),
  parseEntry(386, 'Brandon Hayes'),
  parseEntry(387, 'Victor Brooks'),
  parseEntry(388, 'Chase Ellis'),
  parseEntry(389, 'Roman Cole'),
  parseEntry(390, 'Damian Lewis'),
  parseEntry(391, 'Jordan Grant'),
  parseEntry(392, 'Christian Price'),
  parseEntry(393, 'Noah Fields'),
  parseEntry(394, 'Trevor Carter'),
  parseEntry(395, 'Eric Walker'),
  parseEntry(396, 'Tyson Brooks'),
  parseEntry(397, 'Caleb Hayes'),
  parseEntry(398, 'Mason Turner'),
  parseEntry(399, 'Austin Ross'),
  parseEntry(400, 'Cameron Lewis'),
  parseEntry(401, 'Logan White'),
  parseEntry(402, 'Brandon Cole'),
  parseEntry(403, 'Victor Grant'),
  parseEntry(404, 'Hunter Brooks'),
  // File 1 — South America (IDs 405–424)
  parseEntry(405, 'Diego "Toro" Morales'),
  parseEntry(406, 'Rafael Costa'),
  parseEntry(407, 'Lucas "Fuego" Silva'),
  parseEntry(408, 'Thiago Pereira'),
  parseEntry(409, 'Bruno "Rayo" Mendes'),
  parseEntry(410, 'Matias Rojas'),
  parseEntry(411, 'Emilio "Jaguar" Ortega'),
  parseEntry(412, 'Joaquin Alvarez'),
  parseEntry(413, 'Nicolas "Sombra" Duarte'),
  parseEntry(414, 'Gabriel Ferreira'),
  parseEntry(415, 'Leandro "Acero" Cruz'),
  parseEntry(416, 'Felipe Vargas'),
  parseEntry(417, 'Renato "Ferro" Santos'),
  parseEntry(418, 'Tomas Herrera'),
  parseEntry(419, 'Eduardo "Lobo" Campos'),
  parseEntry(420, 'Cesar Medina'),
  parseEntry(421, 'Victor "Furia" Navarro'),
  parseEntry(422, 'Daniel Gomez'),
  parseEntry(423, 'Hugo "Puma" Castillo'),
  parseEntry(424, 'Ignacio Flores'),
  // File 1 — Russia / Eastern Europe (IDs 425–439)
  parseEntry(425, 'Ivan "Bear" Volkov'),
  parseEntry(426, 'Sergei Petrov'),
  parseEntry(427, 'Dmitri "Iron" Sokolov'),
  parseEntry(428, 'Viktor Lebedev'),
  parseEntry(429, 'Pavel "Wolf" Morozov'),
  parseEntry(430, 'Mikhail Orlov'),
  parseEntry(431, 'Yuri "Steel" Kozlov'),
  parseEntry(432, 'Anton Romanov'),
  parseEntry(433, 'Kirill "Hammer" Zaitsev'),
  parseEntry(434, 'Denis Volodin'),
  parseEntry(435, 'Andrei "Frost" Makarov'),
  parseEntry(436, 'Alexei Smirnov'),
  parseEntry(437, 'Oleg "Titan" Baranov'),
  parseEntry(438, 'Roman Belov'),
  parseEntry(439, 'Nikita "Blizzard" Voronin'),
  // File 1 — Western / Central Europe (IDs 440–449) — country stripped
  parseEntry(440, 'Liam "Rook" Murphy (Ireland)'),
  parseEntry(441, 'Matteo Ricci (Italy)'),
  parseEntry(442, 'Luca "Storm" Moretti (Italy)'),
  parseEntry(443, 'Erik Andersen (Denmark)'),
  parseEntry(444, 'Hugo "Slate" Laurent (France)'),
  parseEntry(445, 'Oliver Bennett (England)'),
  parseEntry(446, 'Stefan "Iron" Novak (Croatia)'),
  parseEntry(447, 'Tomasz Kowalski (Poland)'),
  parseEntry(448, 'Nico "Shadow" Weber (Germany)'),
  parseEntry(449, 'Adrien Dupont (France)'),
  // File 1 — Asia (IDs 450–452) — country stripped
  parseEntry(450, 'Kenji "Dragon" Sato (Japan)'),
  parseEntry(451, 'Min-Jun Park (South Korea)'),
  parseEntry(452, 'Wei "Tiger" Chen (China)'),
  // File 1 — Africa (IDs 453–454) — country stripped
  parseEntry(453, 'Kofi "Lion" Mensah (Ghana)'),
  parseEntry(454, 'Themba Ndlovu (South Africa)'),
  // --- NEW FIGHTERS: File 2 — North America (IDs 455–654) ---
  parseEntry(455, 'Vincent "Knuckles" Marshall'),
  parseEntry(456, 'Curtis "Hawk" Boone'),
  parseEntry(457, 'Raymond Alvarez'),
  parseEntry(458, 'Derrick "Brick" Holloway'),
  parseEntry(459, 'Wesley Griffin'),
  parseEntry(460, 'Maurice "Frost" Chandler'),
  parseEntry(461, 'Terrell Vaughn'),
  parseEntry(462, 'Preston "Rush" Malone'),
  parseEntry(463, 'Donovan Pierce'),
  parseEntry(464, 'Travis "Savage" Kent'),
  parseEntry(465, 'Miles Sutton'),
  parseEntry(466, 'Cedric "Iron" Owens'),
  parseEntry(467, 'Ronnie Beck'),
  parseEntry(468, 'Garrett "Strike" Flynn'),
  parseEntry(469, 'Lionel Grant'),
  parseEntry(470, 'Isaiah Burke'),
  parseEntry(471, 'Desmond "Jet" Monroe'),
  parseEntry(472, 'Franklin Rhodes'),
  parseEntry(473, 'Elijah Vaughn'),
  parseEntry(474, 'Nathan "Steel" Barrett'),
  parseEntry(475, 'Colton Ramsey'),
  parseEntry(476, 'Julius Crawford'),
  parseEntry(477, 'Gavin "Rogue" Bennett'),
  parseEntry(478, 'Spencer Cole'),
  parseEntry(479, 'Elijah Thornton'),
  parseEntry(480, 'Bryce Holloway'),
  parseEntry(481, 'Randall "Smoke" Benson'),
  parseEntry(482, 'Cooper Drake'),
  parseEntry(483, 'Trevor Hollowell'),
  parseEntry(484, 'Tristan "Blitz" Mercer'),
  parseEntry(485, 'Dominic Harper'),
  parseEntry(486, 'Austin Holloway'),
  parseEntry(487, 'Corey Steele'),
  parseEntry(488, 'Landon Rivers'),
  parseEntry(489, 'Malcolm Bryant'),
  parseEntry(490, 'Darren "Venom" Holloway'),
  parseEntry(491, 'Joel Ramsey'),
  parseEntry(492, 'Brandon Givens'),
  parseEntry(493, 'Ryan Collins'),
  parseEntry(494, 'Seth Kramer'),
  parseEntry(495, 'Dillon Hart'),
  parseEntry(496, 'Terrance "Razor" Walton'),
  parseEntry(497, 'Victor Benson'),
  parseEntry(498, 'Kaden Pierce'),
  parseEntry(499, 'Omar Nash'),
  parseEntry(500, 'Julian Reeves'),
  parseEntry(501, 'Malik Thornton'),
  parseEntry(502, 'Preston Ellis'),
  parseEntry(503, 'Zane "Wolf" Barrett'),
  parseEntry(504, 'Evan Brooks'),
  parseEntry(505, 'Derrick Sloan'),
  parseEntry(506, 'Jace Whitaker'),
  parseEntry(507, 'Tyson Barrett'),
  parseEntry(508, 'Kameron Hill'),
  parseEntry(509, 'Caleb Sutton'),
  parseEntry(510, 'Nolan Grant'),
  parseEntry(511, 'Easton Collins'),
  parseEntry(512, 'Andre "Flint" Holloway'),
  parseEntry(513, 'Marcus Givens'),
  parseEntry(514, 'Dylan Barrett'),
  parseEntry(515, 'Josiah Woods'),
  parseEntry(516, 'Eli Walker'),
  parseEntry(517, 'Xavier Malone'),
  parseEntry(518, 'Keenan Rhodes'),
  parseEntry(519, 'DeAndre "Nova" Cross'),
  parseEntry(520, 'Tyrone Griffin'),
  parseEntry(521, 'Caleb Reeves'),
  parseEntry(522, 'Ashton Price'),
  parseEntry(523, 'Gavin Mercer'),
  parseEntry(524, 'Roman Briggs'),
  parseEntry(525, 'Ethan Barrett'),
  parseEntry(526, 'Justin Cross'),
  parseEntry(527, 'Christian Sloan'),
  parseEntry(528, 'Camden Bell'),
  parseEntry(529, 'Micah Russell'),
  parseEntry(530, 'Jeremiah Burke'),
  parseEntry(531, 'Trevor Owens'),
  parseEntry(532, 'Shawn Ramsey'),
  parseEntry(533, 'Adrian Steele'),
  parseEntry(534, 'Nolan Briggs'),
  parseEntry(535, 'Zayne Walker'),
  parseEntry(536, 'Damian Rivers'),
  parseEntry(537, 'Colby Foster'),
  parseEntry(538, 'Tanner Price'),
  parseEntry(539, 'Jaylen Benson'),
  parseEntry(540, 'Landon Briggs'),
  parseEntry(541, 'Antonio Ellis'),
  parseEntry(542, 'Dominic Sutton'),
  parseEntry(543, 'Corey Barrett'),
  parseEntry(544, 'Marcus Vaughn Jr.'),
  parseEntry(545, 'Isaiah Cross Jr.'),
  parseEntry(546, 'Derrick Benson Jr.'),
  parseEntry(547, 'Travis Holloway Jr.'),
  parseEntry(548, 'Elijah Mercer Jr.'),
  parseEntry(549, 'Julian Rhodes Jr.'),
  parseEntry(550, 'Ryan Barrett Jr.'),
  parseEntry(551, 'Vincent Owens Jr.'),
  parseEntry(552, 'Cameron Foster III'),
  parseEntry(553, 'Preston Bell III'),
  parseEntry(554, 'Darren Vaughn III'),
  parseEntry(555, 'Dominic Marshall IV'),
  parseEntry(556, 'Jalen Brooks'),
  parseEntry(557, 'Zach Holloway'),
  parseEntry(558, 'Quincy Marshall'),
  parseEntry(559, 'Terrence Givens'),
  parseEntry(560, 'Malik Rivers'),
  parseEntry(561, 'Cody Barrett'),
  parseEntry(562, 'Evan Steele'),
  parseEntry(563, 'Wesley Sloan'),
  parseEntry(564, 'Jordan Hollowell'),
  parseEntry(565, 'Noah Vaughn'),
  parseEntry(566, 'Brandon Mercer'),
  parseEntry(567, 'Austin Ramsey'),
  parseEntry(568, 'Bryce Bell'),
  parseEntry(569, 'Tristan Owens'),
  parseEntry(570, 'Joel Briggs'),
  parseEntry(571, 'Tyson Rivers'),
  parseEntry(572, 'Garrett Rhodes'),
  parseEntry(573, 'Cameron Sutton'),
  parseEntry(574, 'Marcus Price'),
  parseEntry(575, 'Caleb Monroe'),
  parseEntry(576, 'Seth Barrett'),
  parseEntry(577, 'Elijah Russell'),
  parseEntry(578, 'Gavin Holloway'),
  parseEntry(579, 'Colton Steele'),
  // From here: normal win-ratio group (IDs 580–654, remaining File 2 North America)
  parseEntry(580, 'Trevor Briggs'),
  parseEntry(581, 'Micah Sloan'),
  parseEntry(582, 'Julian Benson'),
  parseEntry(583, 'Nathan Mercer'),
  parseEntry(584, 'Derrick Cross'),
  parseEntry(585, 'Landon Vaughn'),
  parseEntry(586, 'Christian Ramsey'),
  parseEntry(587, 'Spencer Barrett'),
  parseEntry(588, 'Antonio Brooks'),
  parseEntry(589, 'Donovan Ellis'),
  parseEntry(590, 'Zane Price'),
  parseEntry(591, 'Dylan Rhodes'),
  parseEntry(592, 'Ethan Mercer'),
  parseEntry(593, 'Kameron Holloway'),
  parseEntry(594, 'Ryan Steele'),
  parseEntry(595, 'Corey Rivers'),
  parseEntry(596, 'Bryce Sutton'),
  parseEntry(597, 'Joel Benson'),
  parseEntry(598, 'Wesley Barrett'),
  parseEntry(599, 'Caleb Cross'),
  parseEntry(600, 'Nolan Owens'),
  parseEntry(601, 'Adrian Hollowell'),
  parseEntry(602, 'Justin Briggs'),
  parseEntry(603, 'Quincy Mercer'),
  parseEntry(604, 'Colby Rhodes'),
  parseEntry(605, 'Tyson Steele'),
  parseEntry(606, 'Garrett Rivers'),
  parseEntry(607, 'Jace Barrett'),
  parseEntry(608, 'Terrence Sutton'),
  parseEntry(609, 'Marcus Sloan'),
  parseEntry(610, 'Dominic Cross'),
  parseEntry(611, 'Elijah Benson'),
  parseEntry(612, 'Camden Briggs'),
  parseEntry(613, 'Ryan Vaughn'),
  parseEntry(614, 'Micah Price'),
  parseEntry(615, 'Nathan Holloway'),
  parseEntry(616, 'Dylan Ramsey'),
  parseEntry(617, 'Caleb Brooks'),
  parseEntry(618, 'Jordan Barrett'),
  parseEntry(619, 'Brandon Sloan'),
  parseEntry(620, 'Julian Rivers'),
  parseEntry(621, 'Austin Benson'),
  parseEntry(622, 'Gavin Cross'),
  parseEntry(623, 'Trevor Barrett'),
  parseEntry(624, 'Corey Mercer'),
  parseEntry(625, 'Spencer Rhodes'),
  parseEntry(626, 'Colton Vaughn'),
  parseEntry(627, 'Ethan Briggs'),
  parseEntry(628, 'Wesley Price'),
  parseEntry(629, 'Derrick Sutton'),
  parseEntry(630, 'Donovan Ramsey'),
  parseEntry(631, 'Antonio Barrett'),
  parseEntry(632, 'Tyson Sloan'),
  parseEntry(633, 'Marcus Briggs'),
  parseEntry(634, 'Joel Cross'),
  parseEntry(635, 'Caleb Rivers'),
  parseEntry(636, 'Bryce Mercer'),
  parseEntry(637, 'Justin Barrett'),
  parseEntry(638, 'Ryan Benson'),
  parseEntry(639, 'Adrian Sloan'),
  parseEntry(640, 'Dominic Vaughn'),
  parseEntry(641, 'Garrett Price'),
  parseEntry(642, 'Tristan Briggs'),
  parseEntry(643, 'Kameron Mercer'),
  parseEntry(644, 'Seth Cross'),
  parseEntry(645, 'Christian Barrett'),
  parseEntry(646, 'Dylan Benson'),
  parseEntry(647, 'Micah Vaughn'),
  parseEntry(648, 'Elijah Steele'),
  parseEntry(649, 'Jordan Sloan'),
  parseEntry(650, 'Caleb Ramsey'),
  parseEntry(651, 'Trevor Price'),
  parseEntry(652, 'Colby Briggs'),
  parseEntry(653, 'Nathan Benson'),
  parseEntry(654, 'Gavin Rivers'),
  // File 2 — South America (IDs 655–674)
  parseEntry(655, 'Andres "Viento" Salazar'),
  parseEntry(656, 'Marcelo Nunes'),
  parseEntry(657, 'Fabio "Jaguar" Rocha'),
  parseEntry(658, 'Esteban Castillo'),
  parseEntry(659, 'Rodrigo "Relampago" Mendez'),
  parseEntry(660, 'Victor Araujo'),
  parseEntry(661, 'Cristian "Titan" Paredes'),
  parseEntry(662, 'Diego Villanueva'),
  parseEntry(663, 'Leonardo "Ferro" Batista'),
  parseEntry(664, 'Bruno Duarte'),
  parseEntry(665, 'Paulo "Lince" Carvalho'),
  parseEntry(666, 'Mauricio Farias'),
  parseEntry(667, 'Andres "Toro" Ibarra'),
  parseEntry(668, 'Santiago Velasquez'),
  parseEntry(669, 'Thiago "Impacto" Freitas'),
  parseEntry(670, 'Hector Cardenas'),
  parseEntry(671, 'Luciano "Roca" Mendes'),
  parseEntry(672, 'Ramon Ponce'),
  parseEntry(673, 'Felipe "Furia" Acosta'),
  parseEntry(674, 'Joel Navarro'),
  // File 2 — Russia / Eastern Europe (IDs 675–689)
  parseEntry(675, 'Artyom "Cobra" Klimov'),
  parseEntry(676, 'Ilya Markov'),
  parseEntry(677, 'Konstantin "Steel" Egorov'),
  parseEntry(678, 'Yegor Vasiliev'),
  parseEntry(679, 'Ruslan "Hammer" Fedorov'),
  parseEntry(680, 'Vadim Sorokin'),
  parseEntry(681, 'Boris "Wolf" Chernov'),
  parseEntry(682, 'Timur Abramov'),
  parseEntry(683, 'Gennady "Granite" Karpov'),
  parseEntry(684, 'Leonid Filatov'),
  parseEntry(685, 'Fyodor "North" Belyaev'),
  parseEntry(686, 'Stanislav Vinogradov'),
  parseEntry(687, 'Grigori "Rage" Denisov'),
  parseEntry(688, 'Maksim Yakovlev'),
  parseEntry(689, 'Valery "Ice" Tikhonov'),
  // File 2 — Europe (IDs 690–699) — country stripped
  parseEntry(690, 'Patrick "Stone" O\'Connor (Ireland)'),
  parseEntry(691, 'Enzo Bellini (Italy)'),
  parseEntry(692, 'Marco "Falcon" Giordano (Italy)'),
  parseEntry(693, 'Emil Svensson (Sweden)'),
  parseEntry(694, 'Henri "Forge" Moreau (France)'),
  parseEntry(695, 'Alfie Spencer (England)'),
  parseEntry(696, 'Lukas Novak (Czech Republic)'),
  parseEntry(697, 'Kristof Nagy (Hungary)'),
  parseEntry(698, 'Felix "Shadow" Hartmann (Germany)'),
  parseEntry(699, 'Ruben Madsen (Denmark)'),
  // File 2 — Asia (IDs 700–702) — country stripped
  parseEntry(700, 'Hiro "Blaze" Takahashi (Japan)'),
  parseEntry(701, 'Ji-Hoon Kang (South Korea)'),
  parseEntry(702, 'Arjun "Cobra" Mehta (India)'),
  // File 2 — Africa (IDs 703–704) — country stripped
  parseEntry(703, 'Temba "Rhino" Dlamini (Eswatini)'),
  parseEntry(704, 'Idris Kamara (Sierra Leone)'),
];

// Post-process: mark high-win-ratio fighters (IDs 205–579) and always-undefeated (IDs 205–214)
for (const entry of ROSTER_DATA) {
  if (entry.id >= 205 && entry.id <= 579) {
    entry.highWinRatio = true;
  }
  if (entry.id >= 205 && entry.id <= 214) {
    entry.alwaysUndefeated = true;
    entry.forceUndefeated = true;
  }
}

export const KEY_FIGHTER_IDS = [1, 41, 131, 152, 166, 197, 204];
export const ALWAYS_UNDEFEATED_NEW_IDS = new Set([205, 206, 207, 208, 209, 210, 211, 212, 213, 214]);
export const TOTAL_ROSTER = 704;
export const ACTIVE_ROSTER_SIZE = TOTAL_ROSTER;
export const WEEKLY_FIGHT_COUNT = 150;

export function getRosterDisplayName(entry: RosterEntry, state?: { customFirstName?: string; customNickname?: string; customLastName?: string }): string {
  const first = state?.customFirstName ?? entry.firstName;
  const nick = state?.customNickname ?? entry.nickname;
  const last = state?.customLastName ?? entry.lastName;
  if (nick) {
    return `${first} "${nick}" ${last}`;
  }
  return `${first} ${last}`;
}
